DROP SCHEMA IF EXISTS KOALA_SOFTWARE;
CREATE SCHEMA IF NOT EXISTS KOALA_SOFTWARE;
USE KOALA_SOFTWARE;

CREATE TABLE IF NOT EXISTS EMPLOYEES (
EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
EMPLOYEE_NAME  VARCHAR(50) NOT NULL DEFAULT 'NEW_EMPLOYEE',
DOCUMENT INT,
COMPANY_EMAIL  VARCHAR(60),
PERSONAL_EMAIL VARCHAR(60),
DATE_OF_BIRTH DATE,
WORKING_SINCE DATETIME,
SENIORITY ENUM('ENTRY_LEVEL','JUNIOR','SEMI_SENIOR','SENIOR'),
DEPENDENTS INT DEFAULT 0,
PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE SALARY (
PAYMENT_ID INT NOT NULL AUTO_INCREMENT,
SALARY DECIMAL(8,2),
MEDICAL_INSURANCE ENUM('ACCORD', 'GALENO','MEDIFE','OMINT','OSDE', 'SWISS MEDICAL'),
SALARY_PAYMENT_DATE DATE,
PAYMENT_NUMBER INT,
EMPLOYEE_ID INT NOT NULL,
PRIMARY KEY (PAYMENT_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

CREATE TABLE CLIENTS (
CLIENT_CUIT INT NOT NULL,
CLIENT_NAME VARCHAR(50),
ADDRESS VARCHAR(100),
TELEPHONE VARCHAR(30),
MOBILE VARCHAR(30),
MAIL VARCHAR(100),
WEBSITE VARCHAR(100),
PRIMARY KEY (CLIENT_CUIT)
);

CREATE TABLE PROJECT (
PROJECT_ID INT NOT NULL AUTO_INCREMENT,
PROJECT_NAME VARCHAR(30) NOT NULL DEFAULT 'WITHOUT_PROJECT',
DESCRIPTION VARCHAR(100),
TECHNOLOGIES ENUM('PYTHON', 'JAVASCRIPT', 'JAVA', 'NODE', 'OTHER'),
START_DATE DATETIME,
END_DATE DATE,
BUDGET DECIMAL(10,2),
EMPLOYEE_ID INT NOT NULL,
CLIENT_CUIT INT NOT NULL,
PRIMARY KEY (PROJECT_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
FOREIGN KEY (CLIENT_CUIT) REFERENCES CLIENTS (CLIENT_CUIT)
);

CREATE TABLE QUOTATIONS (
QUOTATION_ID INT NOT NULL AUTO_INCREMENT,
QUOTATION_NUMBER INT,
AMOUNT DECIMAL(10,2),
QUOTATION_DATE DATETIME,
DESCRIPTION VARCHAR(300),
QUOTATION_STATUS ENUM('WON', 'LOST', 'NEGOTIATION'),
CLIENT_CUIT INT NOT NULL,
PRIMARY KEY (QUOTATION_ID),
FOREIGN KEY (CLIENT_CUIT) REFERENCES CLIENTS (CLIENT_CUIT)
);

CREATE TABLE INVOICES (
INVOICE_ID INT NOT NULL AUTO_INCREMENT,
AMOUNT DECIMAL(10,2),
INVOICE_DATE DATETIME,
PAYMENT_DATE DATE,
INVOICE_NUMBER INT,
DESCRIPTION VARCHAR(100),
INVOICE_STATUS ENUM('PAID', 'IN PROGRESS', 'ARREARS'),
PAYMENT_METHOD ENUM('CASH', 'WIRE', 'CHECK', 'CREDITCARD'),
CLIENT_CUIT INT NOT NULL,
PRIMARY KEY (INVOICE_ID),
FOREIGN KEY (CLIENT_CUIT) REFERENCES CLIENTS (CLIENT_CUIT)
);
